### ISSUE TITLE
[MAINTAIN] orange: waiting for release which fit on python 3.12

### ISSUE THREAD

**Issue by Kiri2002** [BioArchLinux/Packages#211]
**Log of the bug**

<details>

```
Traceback (most recent call last):
  File "/build/python-orange-widget-base/src/orange-widget-base-4.23.0/setup.py", line 179, in <module>
    setup_package()
  File "/build/python-orange-widget-base/src/orange-widget-base-4.23.0/setup.py", line 153, in setup_package
    write_version_py()
  File "/build/python-orange-widget-base/src/orange-widget-base-4.23.0/setup.py", line 122, in write_version_py
    import imp
ModuleNotFoundError: No module named 'imp'

```
 
 </details>

**Packages (please complete the following information):**
 - orange
 - python-orange-widget-base

**Description**
The upstream is trying to fix, and waiting to release, see:

https://github.com/biolab/orange3/issues/6738

**Comment by Kiri2002** [comment]
adressed
